language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS myfarm_test;'
# addons:
#   - postgres: ""
script:
  - coveralls
  - coverage
  - pytest --cov=statisticsapi/
after_script:
  -coveralls
  
